<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="ADTLibrary">
      <HintPath>..\ADTLibrary\bin\Debug\net8.0\ADTLibrary.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
